version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    volumes:
      - ./pinterest
    ports:
      - "3001:3000"
    depends_on:
      - db
    restart: on-failure
    environment:
      PGHOST: "db"
      PGUSER: "postgres"
      PGDBNAME: "pinterest_production"
